// 용어집 — 도구 화면에 등장하는 지표·용어의 정의, 계산식, 해석, 출처. 관리자 탭에서 표시.
// 항목을 추가하려면 이 배열에 넣기만 하면 된다 (탭에서 검색·분류 필터 제공).

export interface GlossaryTerm {
  term: string;            // 표시 용어
  en?: string;             // 영문/약어
  category: string;        // 분류
  definition: string;      // 한 줄 정의
  formula?: string;        // 계산식 (도구 내부 구현 기준)
  reading?: string;        // 해석 방법 / 실무 판단
  source?: string;         // 데이터 출처·갱신 주기
  where?: string;          // 도구 내 위치
}

export const GLOSSARY_CATEGORIES = ['시장 가격', '수급', '스프레드·연관시장', '계약·스펙', '재고·리스크', '전략·분석', '데이터·자동화'] as const;

export const GLOSSARY: GlossaryTerm[] = [
  // ── 시장 가격 ──
  { term: 'FCPO', en: 'Crude Palm Oil Futures (Bursa Malaysia)', category: '시장 가격',
    definition: '말레이시아 부르사 거래소 팜유 선물. 세계 팜유 가격의 기준 지표.',
    reading: '도구의 시세 DB는 BMD 일일 보고서의 RBD PALM OIL 물리 호가(USD/MT)를 월물별로 저장한 것. 정확히는 FCPO 선물이 아니라 그 기준으로 형성되는 RBD 팜유 현물 호가.',
    source: 'BMD PDF·텍스트 수동 입력 (매일)', where: 'FCPO 가격 탭' },
  { term: '월물', en: 'Contract month', category: '시장 가격',
    definition: '선적(인도) 월 기준으로 구분된 가격. 2026-10 월물 = 10월 선적분 가격.',
    reading: 'BMD 호가는 M1~M3(근월 3개)와 Q1~Q3(분기)로 나오며 도구에서는 분기를 월로 펼쳐 저장하므로 4개월 이후는 분기 단위로 같은 값이 반복된다.' },
  { term: '근월 / 원월', en: 'Front month / Deferred', category: '시장 가격',
    definition: '근월 = 가장 가까운 선적월의 가격, 원월 = 그보다 뒤 월물 가격.' },
  { term: '월물 곡선', en: 'Term structure', category: '시장 가격',
    definition: '기준일에 월물별 가격을 근월→원월 순으로 이은 곡선.',
    formula: '근월 대비 스프레드 = 원월가 − 근월가 / 월당 캐리 = 스프레드 ÷ 개월 수',
    reading: '콘탱고(원월 > 근월): 시장이 현재 물량을 여유 있게 봄, 원월 선계약은 월당 캐리만큼 프리미엄을 미리 내는 셈 → 근월 위주 분할이 유리. 백워데이션(근월 > 원월): 현물 타이트, 재고 커버가 허용되면 원월 계약이 유리.',
    where: 'FCPO 가격 탭 상단' },
  { term: '콘탱고 / 백워데이션', en: 'Contango / Backwardation', category: '시장 가격',
    definition: '원월이 근월보다 비싸면 콘탱고, 싸면 백워데이션.',
    reading: 'M1−M3 스프레드의 180일 백분위가 80% 이상이면 콘탱고 심화 구간, 20% 이하면 백워데이션 심화 구간.' },
  { term: '박스권 분석 (V3)', en: 'Box range', category: '시장 가격',
    definition: '20일 이동평균과 표준편차로 현재가가 어느 구매 구간에 있는지 판정하는 엑셀 V3 로직의 재현.',
    formula: '전량구매 상한 = MA20 − σ / 적극구매 상한 = MA20 − 0.5σ / 모니터링 상한 = MA20 + 0.5σ / 최소구매 상한 = 20일 최고가. 전쟁이슈 모드는 현재가 ± σ×배수 + 리스크 프리미엄',
    reading: '전량구매 → 100% 확보, 적극구매 → 70~80%, 모니터링 → 30~50% 분할, 최소구매/구매대기 → 필수물량만.',
    where: '박스권 분석 탭, 대시보드 게이지' },
  { term: 'RSI (14)', en: 'Relative Strength Index', category: '시장 가격',
    definition: '최근 14일 상승폭과 하락폭의 비율로 과매수·과매도를 보는 지표(0~100).',
    reading: '70 이상 과매수, 30 이하 과매도. 팜유는 수급·정책 영향이 커서 보조 확인용.', where: '박스권 분석 탭' },
  { term: 'MACD (12,26,9)', en: 'Moving Average Convergence Divergence', category: '시장 가격',
    definition: '12일·26일 지수이동평균 차이(MACD)와 그 9일 평균(Signal)의 관계로 모멘텀 방향을 봄.',
    reading: '히스토그램(MACD − Signal)이 양수로 전환하면 상승 전환, 음수로 전환하면 하락 전환.' },
  { term: '볼린저 %B', en: 'Bollinger %B', category: '시장 가격',
    definition: '20일 평균 ±2σ 밴드 안에서 현재가의 위치(0=하단, 1=상단).',
    reading: '0.2 이하 하단권(과매도), 0.8 이상 상단권(과열).' },
  { term: 'ATR (14)', en: 'Average True Range', category: '시장 가격',
    definition: '최근 14일 일평균 가격 변동폭. 도구는 고가·저가가 없어 종가 변화 절대값으로 계산.',
    reading: '분할 매수 간격이나 손절 폭을 정할 때 참고.' },

  // ── 수급 ──
  { term: 'MPOB', en: 'Malaysian Palm Oil Board', category: '수급',
    definition: '말레이시아 팜유청. 매월 10일 전후 전월 생산·수출·재고 통계를 발표하며 시장이 가장 주목하는 수급 지표.',
    source: 'MPOB BEPI 사이트 자동 수집 (매월 12·22일)', where: 'MPOB 수급 탭' },
  { term: '총재고', en: 'Closing stock of palm oil', category: '수급',
    definition: '말레이시아 월말 팜유 재고 합계(CPO + 가공유). 시장이 말하는 "말레이시아 재고"가 이 숫자.',
    reading: '전 기간 백분위 80% 이상이면 역사적 고점권(약세 압력), 20% 이하면 저점권.' },
  { term: 'CPO 생산', en: 'Crude palm oil production', category: '수급',
    definition: '말레이시아 월별 원유(CPO) 생산량. 3~10월 증산기, 11~2월 감산기의 계절성.' },
  { term: '재고/수출 비율', en: 'Stock-to-export ratio', category: '수급',
    definition: '기말재고 ÷ 당월 수출량. 수출 몇 개월치 재고를 들고 있는지(재고 커버리지).',
    formula: '총재고 ÷ 팜유 수출 (개월)',
    reading: '전 기간 평균 대비 20% 이상 높으면 공급 여유(하방 압력), 20% 이상 낮으면 타이트(상방 압력).', where: 'MPOB 탭 > 수급 밸런스' },
  { term: '재고/소비 비율', en: 'Stock-to-use ratio', category: '수급',
    definition: '기말재고 ÷ (수출 + 추정 내수). 국제 곡물 시장의 표준 수급 지표.',
    formula: '추정 내수 = 기초재고 + 생산 − 수출 − 기말재고 (수입 무시 → 과소 가능, 참고용)' },
  { term: '수급 적정가', en: 'Fundamental fair value', category: '수급',
    definition: '재고/수출 비율과 FCPO 월평균의 회귀식으로 현재 비율에서 기대되는 가격.',
    formula: '가격 = a + b × 재고/수출 비율 (전 기간 최소제곱)',
    reading: '현재가가 적정가보다 8% 이상 높으면 수급 대비 고평가. 단일 변수라 r(상관계수)이 낮으면 참고만.' },
  { term: 'USDA PSD', en: 'Production, Supply & Distribution', category: '수급',
    definition: '미국 농무부의 국가별 농산물 수급 전망. 중국·인도 등의 팜유 수입·소비·재고를 마케팅연도(10월~9월) 기준으로 매월 갱신.',
    source: 'USDA FAS API (USDA_API_KEY, 매월 MPOB cron 편승)', where: 'MPOB 탭 > 세계 수급' },

  // ── 스프레드·연관시장 ──
  { term: 'POGO 스프레드', en: 'Palm Oil − Gas Oil', category: '스프레드·연관시장',
    definition: '팜유 가격에서 경유(가스오일) 가격을 뺀 값. 바이오디젤 업계의 대표 지표.',
    formula: '팜유(USD/MT) − Heating Oil(USD/gal × 315). 원래는 ICE 가스오일 기준이나 무료 소스가 없어 NYMEX Heating Oil 대용',
    reading: '음수(팜유가 경유보다 쌈) = 바이오디젤 원료로 유리 → 에너지 수요가 팜유 가격을 지지. 양수 = 전환 유인 약화, 팜유 약세 요인.',
    source: 'Yahoo Finance 매일 07:30 자동', where: '대두유 탭, 대시보드 한 줄' },
  { term: '팜유−원유 스프레드', en: 'Palm − Brent', category: '스프레드·연관시장',
    definition: '팜유 − Brent 원유(bbl×7.33 환산). 원유는 정제 전 가격이라 경유보다 항상 낮게 나오는 참고치.' },
  { term: '대두유 스프레드', en: 'Soybean oil − Palm oil', category: '스프레드·연관시장',
    definition: 'CBOT 대두유(USD/MT 환산) − 팜유. 팜유의 상대 가격 매력도.',
    formula: '대두유 cents/lb × 22.046 = USD/MT',
    reading: '스프레드가 커지면(팜유 상대적으로 쌈) 팜유로 수요 이동 → 팜유 지지. 축소되면 반대.' },
  { term: '대련 팜올레인 (DCE)', en: 'Dalian Commodity Exchange P contract', category: '스프레드·연관시장',
    definition: '중국 대련상품거래소 팜올레인 선물 주력월물(CNY/t). 중국 내 팜유 가격.',
    formula: 'USD 환산 = CNY/t ÷ USD/CNY',
    reading: '대련가 − FCPO(중국 수입 채산성): 대련가는 증치세 9%·물류 포함 국내가라 평상시 +150~250 수준. 그 아래로 축소되면 중국 수입 수요 둔화 신호. 중국 내 대두유−팜유가 음수면 중국 수요가 대두유로 이동.',
    source: 'Sina Finance 일봉 (DCE 공식 사이트는 봇 차단)' },
  { term: 'USD/MYR', category: '스프레드·연관시장',
    definition: '달러/링깃 환율. FCPO는 링깃 표시라 링깃 약세면 달러 기준 팜유가 싸진다.', source: 'ECB(frankfurter) 매일' },
  { term: 'USD/KRW', category: '스프레드·연관시장',
    definition: '달러/원 환율. 선구매 효과의 원화 환산과 예산 영향에 사용. 계약별 환율은 구매이력에서 건별 입력.' },

  // ── 계약·스펙 ──
  { term: 'RBD 팜유', en: 'Refined, Bleached, Deodorized Palm Oil', category: '계약·스펙',
    definition: '정제·탈색·탈취 팜유. 일반 팜유(RPO)의 기준 스펙이며 시황가의 기준.' },
  { term: 'RSPO (MB)', en: 'Roundtable on Sustainable Palm Oil, Mass Balance', category: '계약·스펙',
    definition: '지속가능 팜유 인증. MB(Mass Balance)는 인증유와 일반유를 물리적으로 섞되 장부상 인증량을 관리하는 방식.',
    reading: '프리미엄 +25달러(공급사 공통).' },
  { term: '3-MCPD', en: '3-monochloropropane-1,2-diol', category: '계약·스펙',
    definition: '정제 과정(고온 탈취)에서 생기는 유해물질. EU 규제(2.5 ppm 이하)로 관리 스펙이 필요.',
    reading: '관리팜유의 기본 속성. 프리미엄 +10달러(공급사 공통).' },
  { term: 'GE', en: 'Glycidyl Esters', category: '계약·스펙',
    definition: '3-MCPD와 함께 생기는 유해물질(EU 기준 1.0 ppm 이하). 유럽 수출 제품용.',
    reading: '프리미엄 +30~35달러로 공급사·시점별로 다름 → 계약별로 저장하고 공급사 벤치마크로 비교.' },
  { term: '관리팜유', en: 'Managed palm oil', category: '계약·스펙',
    definition: 'Low 3-MCPD 를 기본으로 GE·RSPO 가 조합된 팜유. 도구에서는 RSPO 여부로 관리팜유 RPO / 관리팜유 RSPO 두 제품으로 관리하고, 세부 스펙(3-MCPD / +GE / +RSPO / +GE+RSPO)은 계약별로 기록.',
    where: '구매이력·재고관리·선구매 효과' },
  { term: 'Base 가격 (RBD 환산가)', en: 'Base price', category: '계약·스펙',
    definition: '계약 단가에서 스펙 프리미엄을 뺀 값. 협상 시 공급사가 제시하는 RBD 기준가.',
    formula: 'Base = 단가 − (3-MCPD + GE + RSPO 프리미엄)',
    reading: '스펙이 다른 계약끼리, 그리고 시황(RBD)과 같은 기준으로 비교하려면 Base 로 본다. 백테스트의 "실제 계약"도 Base 기준.' },
  { term: '프리미엄 벤치마크', category: '계약·스펙',
    definition: '공급사×스펙별로 실제 지불한 3-MCPD·GE·RSPO 프리미엄의 물량 가중 평균.',
    reading: '다음 비딩에서 "지난번 GE 30이었다"는 협상 근거.', where: '구매이력 탭 > 선구매 효과 분석' },
  { term: '선적월 / 통관월', category: '계약·스펙',
    definition: '선적월 = 계약상 선적 시점, 통관월 = 선적월 + 1개월(도구 규칙). 재고관리의 통관수량은 구매이력 선적월+1M 로 자동 반영.' },
  { term: 'D/P at sight · L/C at sight · CAD', category: '계약·스펙',
    definition: '결제조건. D/P(일람불 인수도), L/C(일람불 신용장), CAD(서류 인도 후 지급). IOI 는 D/P·CAD, Wilmar 는 L/C 관행.' },

  // ── 재고·리스크 ──
  { term: '기말재고', category: '재고·리스크',
    definition: '월말 재고(kg).', formula: '전월 기말 + 통관수량 − 예상소요 − 판매량. 실재고 반영값이 있으면 그 값으로 대체하고 다음 달부터 이어 계산',
    where: '재고관리 탭' },
  { term: '실재고 반영값', en: 'Actual ending stock', category: '재고·리스크',
    definition: '삼양베이커 수불 등 실사 재고로 계산값을 덮어쓰는 입력. 엑셀의 "삼양베이커수불 재고 적용" 하드코딩과 동일.',
    reading: '기말재고 셀을 클릭해 입력, ✕ 로 해제.' },
  { term: '재고회전(개월)', category: '재고·리스크',
    definition: '기말재고 ÷ 당월 예상소요. 몇 개월치 재고인가. 엑셀 재고회전일과 동일.',
    reading: '소요가 달라지는 달(투입 개시·RPO/RSPO 구분 투입·전환 종료)에는 실제 소진 기간과 어긋남 — 관리팜유 RSPO 9월은 소요 2,496톤 기준 0.6 이지만 10월부터 소요가 520톤이라 실제는 3개월+. 대시보드 카드·구매 알람은 선행 커버를 우선 사용.',
    where: '재고관리 탭' },
  { term: '선행 커버(개월)', en: 'Forward coverage (months of supply)', category: '재고·리스크',
    definition: '기말재고가 다음 달부터의 예상소요를 몇 개월 감당하는지. 통관 예정량은 넣지 않고 지금 재고만으로 계산.',
    formula: '다음 달부터 예상소요를 차례로 빼며 개월 수를 세고, 마지막 달은 남은 재고 ÷ 그 달 소요로 분수 처리. 데이터 범위 끝까지 재고가 남으면 "+" (하한값)',
    reading: '2.5 이하 경고, 1.5 이하 긴급(구매 알람 기준). "+" 가 붙은 하한값은 2.5 를 넘길 때만 채택하고 아니면 재고회전으로 판단.',
    where: '대시보드 재고 카드, 구매 알람' },
  { term: '구매 알람', category: '재고·리스크',
    definition: '재고 흐름에서 기말재고가 음수가 되는 첫 달을 찾아 3개월 전을 권장 선적월로 제시. 소진월이 없으면 선행 커버(향후 소요 데이터가 없으면 재고회전)로 경고·긴급 판단.',
    reading: '당월·향후 예상소요가 모두 0인 제품(운영 전·관리팜유 전환 종료)은 알림 대상에서 제외.' },
  { term: '미확정 물량', en: 'Uncovered volume', category: '재고·리스크',
    definition: '향후 6개월 재고 흐름에서 기말재고가 0 아래로 내려가는 누적분 = 추가로 계약해야 하는 물량.', where: '구매 알람 탭 > 리스크 노출' },
  { term: 'VaR 95%', en: 'Value at Risk', category: '재고·리스크',
    definition: '95% 신뢰수준에서 리드타임 동안 불리하게 움직일 수 있는 가격 변동 × 미확정 물량.',
    formula: '1.645 × 일변동성(60일 σ) × √영업일(1개월 21, 3개월 63) × 기준가 × 물량',
    reading: '"지금 안 사면 최악의 경우 이만큼 더 든다"의 크기.' },
  { term: '계획단가', category: '재고·리스크',
    definition: '연간 경영계획 단가(USD/MT). 올해 계약 가중평균 + 잔여 미계약분을 현재가로 샀을 때의 연간 예상 평균과 비교.',
    reading: '구매 알람 탭에서 제품별로 클릭해 입력.' },

  // ── 전략·분석 ──
  { term: '선구매 효과', en: 'Prebuy effect', category: '전략·분석',
    definition: '미리 계약한 가격과 선적월 시황가의 차이로 본 절감(또는 초과) 금액.',
    formula: '효과 = (시황가 + 스펙 프리미엄 − 계약단가) × 물량 × 환율. 양수 = 절감',
    where: '구매이력 탭 > 선구매 효과 분석, 대시보드 실적표' },
  { term: '구매 당월시황 (시황가)', category: '전략·분석',
    definition: '선적월이 도래했을 때의 시장가(RBD 기준). 선구매를 안 했으면 냈을 가격.',
    formula: '선적월 동안 거래된 해당 월물 종가의 평균 (엑셀 "구매 당월시황"과 동일)',
    reading: '시황가 자동 매칭 버튼으로 FCPO DB에서 채움. 손으로 넣은 값은 보존.' },
  { term: '전략 백테스트', category: '전략·분석',
    definition: '계약 가능 기간(선적월 3개월 전~1개월 전)에 여러 전략으로 샀을 때의 단가를 과거 데이터로 비교.',
    reading: '기간 내 백분위 = 그 전략이 산 가격이 몇 번째로 쌌는지(0%=최저). 실제 계약이 기간 평균보다 싸고 백분위가 50% 아래면 타이밍이 가치를 냈다는 뜻.',
    where: '구매이력 탭 > 전략 백테스트' },
  { term: '변곡점', en: 'Inflection point', category: '전략·분석',
    definition: '전일 대비 등락률로 시황을 자동 분류(≥+1% 강세, −1~−2.5% 약세, ≤−2.5% 급락)한 날짜 표시.' },
  { term: '관리팜유 투입 시뮬레이터', category: '전략·분석',
    definition: '기존 RPO+RSPO 재고를 영업일 소요로 소진하고, 관리팜유 투입 시작일에 따라 소진일과 미소진 물량을 계산.', where: '재고관리 탭' },

  // ── 데이터·자동화 ──
  { term: 'BMD 일일 보고서', category: '데이터·자동화',
    definition: 'Bursa Malaysia Derivatives 일일 시세 PDF. RBD PALM OIL 물리 호가(M1~M3, Q1~Q3)를 AI 로 파싱해 시세 DB에 저장. 유일하게 수동 입력이 남은 데이터.', where: 'FCPO 가격 탭' },
  { term: 'Cron (자동 수집)', category: '데이터·자동화',
    definition: 'Vercel 예약 실행. 환율·원유·경유·대두유·대련은 매일 07:30(KST), MPOB·USDA는 매월 12일·22일 12:00.',
    reading: '실패하면 다음 실행에서 다시 시도. 수동 버튼도 각 탭에 있음.' },
  { term: '시황가 자동 매칭', category: '데이터·자동화',
    definition: '구매이력의 선적월별 시황가를 FCPO DB 월평균으로 채우는 기능. 미입력만 채우기 / 전체 갱신(수동 입력 보존).' },
  { term: '북마클릿 (뉴스)', category: '데이터·자동화',
    definition: 'KoreaPDS 등 시황 페이지에서 클릭 한 번으로 기사를 도구에 보내는 브라우저 즐겨찾기. AI 가 시황(강세/약세/보합)과 영향도를 판정.' },
];
